"""LOS ESTADIOS SEGÚN EL REAL DE CADA CLUB (26-9-2026).

Pedido del usuario: *"los estadios se deben basar en los reales de los equipos
que tenemos"*. Aquí va la ARQUITECTURA del estadio de cada club real (forma,
bandejas, techo, pista de atletismo, focos, fachada y dibujo de las butacas),
no su nombre: la base ficticia la recibe con el nombre ficticio del club
(`base_ficticia.py` -> ESTADIO_CLUB) y el pack real con el nombre real.

Claves = nombre real LIMPIO (sin la cubierta de leetspeak).
Valores: forma (cuenco, oval, rect, caldera, herradura, ingles), niveles (1-3),
techo (sin, parcial, visera, anillo, total, membrana, retractil), pista (bool),
focos (torres, corona, halo, mixto), fachada (hormigon, ladrillo, metal, vidrio,
membrana), rasgo (texto corto del porqué, para la ficha del estadio).
Lo que no está en la tabla sigue con los estilos genéricos de siempre.
"""


def e(forma, niveles, techo, pista=False, focos="torres", fachada="hormigon", rasgo=""):
    return {"forma": forma, "niveles": niveles, "techo": techo, "pista": pista,
            "focos": focos, "fachada": fachada, "rasgo": rasgo}


ESTADIOS = {
    # ------------------------------------------------------------ CHILE
    "Colo-Colo": e("oval", 2, "sin", False, "torres", "hormigon", "Óvalo abierto de hormigón, el más grande del país de un club"),
    "U. de Chile": e("oval", 2, "sin", True, "torres", "hormigon", "Estadio olímpico con pista, a cielo abierto"),
    "U. Católica": e("herradura", 1, "sin", False, "mixto", "hormigon", "Herradura abierta a la cordillera"),
    "Coquimbo Unido": e("rect", 1, "parcial", False, "mixto", "metal", "Cuatro tribunas modernas junto al mar"),
    "Cobresal": e("rect", 1, "sin", False, "torres", "hormigon", "Estadio minero en pleno desierto"),
    "Palestino": e("rect", 1, "sin", False, "torres", "hormigon", "Estadio de barrio con tribuna principal"),
    "Unión Española": e("ingles", 1, "parcial", False, "torres", "ladrillo", "Estadio antiguo, tribunas pegadas a la cancha"),
    "Audax Italiano": e("rect", 1, "parcial", False, "mixto", "metal", "Estadio municipal renovado"),
    "Huachipato": e("ingles", 1, "parcial", False, "mixto", "metal", "Estadio acerero, techado y pegado al campo"),
    "Ñublense": e("rect", 1, "parcial", False, "mixto", "hormigon", ""),
    "O'Higgins": e("rect", 1, "parcial", False, "mixto", "metal", "Estadio mundialista renovado"),
    "Everton": e("cuenco", 1, "sin", False, "torres", "hormigon", "Estadio junto a la laguna, entre cerros"),
    "D. Iquique": e("rect", 1, "parcial", False, "mixto", "metal", ""),
    "La Serena": e("rect", 1, "parcial", False, "mixto", "hormigon", ""),
    "Cobreloa": e("rect", 1, "parcial", False, "torres", "hormigon", "Estadio del desierto, a 2.300 m"),
    "S. Wanderers": e("rect", 1, "parcial", False, "mixto", "hormigon", "Estadio porteño entre cerros"),
    "U. de Concepción": e("rect", 1, "parcial", False, "mixto", "metal", "Estadio mundialista con techo"),
    "D. Concepción": e("rect", 1, "parcial", False, "mixto", "metal", "Estadio mundialista con techo"),
    "Rangers": e("oval", 1, "parcial", True, "torres", "hormigon", "Estadio fiscal con pista"),
    "Antofagasta": e("rect", 1, "parcial", False, "mixto", "hormigon", ""),
    "D. Temuco": e("rect", 1, "parcial", False, "mixto", "hormigon", ""),
    # ------------------------------------------------------------ ARGENTINA
    "Boca Juniors": e("caldera", 3, "sin", False, "torres", "hormigon", "La caldera: tres bandejas casi verticales y un lado de palcos"),
    "River Plate": e("oval", 2, "sin", False, "corona", "hormigon", "Óvalo gigante, el mayor de Sudamérica"),
    "Racing Club": e("cuenco", 2, "sin", False, "torres", "hormigon", "El cilindro de hormigón"),
    "San Lorenzo": e("rect", 2, "sin", False, "torres", "hormigon", ""),
    "Independiente": e("cuenco", 2, "parcial", False, "mixto", "hormigon", "Estadio moderno de dos bandejas"),
    "Estudiantes": e("rect", 2, "parcial", False, "mixto", "metal", "Estadio renovado, tribunas techadas"),
    "Vélez": e("rect", 2, "sin", False, "torres", "hormigon", ""),
    "Huracan": e("rect", 2, "sin", False, "torres", "hormigon", "Tribuna art déco con su torre"),
    "Rosario Central": e("rect", 2, "sin", False, "torres", "hormigon", "El gigante de barrio"),
    "Newell's": e("rect", 2, "sin", False, "torres", "hormigon", ""),
    "Lanús": e("rect", 2, "sin", False, "torres", "hormigon", ""),
    "Talleres": e("oval", 2, "parcial", True, "corona", "hormigon", "Estadio mundialista con pista"),
    "Godoy Cruz": e("oval", 2, "parcial", True, "corona", "hormigon", "Estadio mundialista con pista, al pie de la montaña"),
    # ------------------------------------------------------------ BRASIL
    "Flamengo": e("oval", 2, "anillo", False, "corona", "hormigon", "El templo: óvalo con anillo de techo"),
    "Fluminense": e("oval", 2, "anillo", False, "corona", "hormigon", "El templo: óvalo con anillo de techo"),
    "Palmeiras": e("rect", 2, "anillo", False, "halo", "metal", "Arena moderna pegada al campo"),
    "Sao Paulo": e("oval", 2, "anillo", False, "corona", "hormigon", "Coloso de hormigón"),
    "Gremio": e("rect", 2, "anillo", False, "halo", "metal", "Arena de cuatro tribunas techadas"),
    "Corinthians": e("rect", 2, "parcial", False, "halo", "vidrio", "Arena con fachada de vidrio"),
    "Santos": e("ingles", 1, "sin", False, "torres", "hormigon", "Estadio pequeño y mítico"),
    "Botafogo": e("oval", 2, "anillo", True, "corona", "metal", "Estadio olímpico con pista"),
    "Cruzeiro": e("oval", 2, "anillo", False, "corona", "hormigon", "Coloso ovalado con anillo"),
    "Atl. Mineiro": e("rect", 2, "anillo", False, "halo", "metal", "Arena nueva de cuatro tribunas"),
    "Internacional": e("cuenco", 2, "membrana", False, "halo", "membrana", "Cuenco junto al río con cubierta de membrana"),
    "Vasco": e("herradura", 1, "sin", False, "torres", "hormigon", "Estadio histórico en herradura"),
    "Bahia": e("herradura", 2, "anillo", False, "halo", "metal", "Herradura abierta a un lago"),
    "Fortaleza": e("cuenco", 2, "anillo", False, "corona", "metal", "Cuenco mundialista"),
    "Athletico PR": e("rect", 2, "retractil", False, "halo", "vidrio", "Arena con techo retráctil y césped artificial"),
    # ------------------------------------------------------------ URUGUAY
    "Peñarol": e("rect", 2, "sin", False, "torres", "hormigon", "Estadio propio de cuatro tribunas"),
    "Nacional": e("ingles", 2, "sin", False, "torres", "hormigon", "El más antiguo de América, pegado al campo"),
    "Defensor": e("rect", 1, "sin", False, "torres", "hormigon", "Junto a la rambla"),
    # ------------------------------------------------------------ PARAGUAY
    "Olimpia": e("rect", 1, "parcial", False, "torres", "hormigon", ""),
    "Cerro Porteño": e("caldera", 2, "sin", False, "torres", "hormigon", "La olla: tribunas empinadas y cerradas"),
    "Libertad": e("rect", 1, "parcial", False, "mixto", "hormigon", ""),
    # ------------------------------------------------------------ COLOMBIA
    "Atl. Nacional": e("oval", 2, "parcial", True, "corona", "hormigon", "Estadio con pista y tribuna cubierta"),
    "DIM Medellin": e("oval", 2, "parcial", True, "corona", "hormigon", "Estadio con pista y tribuna cubierta"),
    "Millonarios": e("rect", 2, "parcial", False, "mixto", "hormigon", "Estadio clásico de la capital"),
    "Santa Fe": e("rect", 2, "parcial", False, "mixto", "hormigon", "Estadio clásico de la capital"),
    "America de Cali": e("oval", 2, "parcial", True, "corona", "hormigon", "Estadio con pista"),
    "Dep. Cali": e("rect", 2, "sin", False, "torres", "hormigon", "Estadio propio de dos bandejas"),
    "Junior": e("oval", 2, "sin", False, "torres", "hormigon", "Estadio abierto del Caribe"),
    # ------------------------------------------------------------ PERÚ
    "Universitario": e("cuenco", 3, "sin", False, "torres", "hormigon", "Monumental: tres bandejas, el más grande del país"),
    "Alianza Lima": e("rect", 2, "sin", False, "torres", "hormigon", "Estadio de barrio popular"),
    "Sporting Cristal": e("oval", 2, "parcial", True, "corona", "hormigon", "Estadio nacional con pista"),
    "Melgar": e("oval", 1, "sin", True, "torres", "hormigon", "Estadio con pista al pie del volcán"),
    # ------------------------------------------------------------ ECUADOR
    "LDU Quito": e("rect", 2, "sin", False, "torres", "hormigon", "Estadio en la altura"),
    "Barcelona SC": e("cuenco", 2, "sin", False, "torres", "hormigon", "Monumental de dos anillos"),
    "Emelec": e("rect", 2, "parcial", False, "mixto", "hormigon", ""),
    "I. del Valle": e("rect", 1, "parcial", False, "mixto", "metal", ""),
    # ------------------------------------------------------------ ESPAÑA
    "Real Madrid": e("rect", 3, "retractil", False, "halo", "metal", "Tres bandejas, techo retráctil y piel metálica"),
    "Barcelona": e("cuenco", 3, "anillo", False, "halo", "hormigon", "El coloso de tres anillos"),
    "Atlético Madrid": e("cuenco", 2, "membrana", False, "halo", "membrana", "Cuenco con cubierta de membrana"),
    "Sevilla": e("cuenco", 2, "parcial", False, "mixto", "hormigon", "Mosaico en la fachada"),
    "Valencia": e("rect", 3, "parcial", False, "torres", "hormigon", "Gradas muy empinadas"),
    "Villarreal": e("rect", 2, "parcial", False, "mixto", "metal", ""),
    "Ath. Bilbao": e("rect", 2, "anillo", False, "halo", "membrana", "Fachada blanca iluminable"),
    "Real Sociedad": e("rect", 2, "anillo", False, "halo", "metal", "Estadio renovado sin pista"),
    "Betis": e("rect", 2, "parcial", False, "mixto", "hormigon", ""),
    "Celta Vigo": e("rect", 2, "parcial", False, "mixto", "hormigon", ""),
    "Osasuna": e("rect", 2, "total", False, "halo", "metal", "Techado entero, sonoro"),
    "Espanyol": e("cuenco", 2, "anillo", False, "halo", "metal", ""),
    "Rayo Vallecano": e("herradura", 1, "sin", False, "torres", "hormigon", "Tres tribunas y un muro de edificios"),
    # ------------------------------------------------------------ INGLATERRA
    "Manchester Utd": e("ingles", 2, "anillo", False, "corona", "ladrillo", "Teatro de los sueños, tribunas de ladrillo"),
    "City de Manch.": e("cuenco", 3, "anillo", False, "corona", "metal", "Cuenco con mástiles de techo"),
    "Liverpool": e("ingles", 2, "parcial", False, "corona", "ladrillo", "Tribuna gigante en un fondo"),
    "Arsenal": e("cuenco", 2, "anillo", False, "halo", "vidrio", "Cuenco moderno de vidrio"),
    "Chelsea": e("ingles", 2, "anillo", False, "corona", "ladrillo", ""),
    "Tottenham": e("ingles", 3, "anillo", False, "halo", "vidrio", "Muro de una bandeja en un fondo"),
    "Newcastle": e("ingles", 2, "anillo", False, "corona", "metal", "Estadio en lo alto de la ciudad"),
    "Aston Villa": e("ingles", 2, "anillo", False, "corona", "ladrillo", "Fachada de ladrillo clásica"),
    "West Ham": e("oval", 2, "anillo", False, "corona", "membrana", "Antiguo estadio olímpico"),
    "Everton FC": e("rect", 2, "anillo", False, "halo", "ladrillo", "Estadio nuevo de ladrillo junto al río"),
    "Brighton": e("cuenco", 2, "anillo", False, "halo", "metal", "Techo en arco"),
    "Wolves": e("ingles", 2, "anillo", False, "corona", "metal", ""),
    "Cristal Palace": e("ingles", 1, "parcial", False, "torres", "ladrillo", ""),
    "Fulham": e("ingles", 1, "parcial", False, "torres", "ladrillo", "Casita de ladrillo junto al Támesis"),
    "Brentford": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Nottingham F.": e("ingles", 2, "anillo", False, "corona", "ladrillo", "Junto al río"),
    # ------------------------------------------------------------ ITALIA
    "Juventus": e("rect", 2, "anillo", False, "halo", "metal", "Estadio propio de dos bandejas"),
    "Milan": e("cuenco", 3, "anillo", False, "corona", "hormigon", "Tres anillos y torres de rampas"),
    "Inter": e("cuenco", 3, "anillo", False, "corona", "hormigon", "Tres anillos y torres de rampas"),
    "Napoli": e("oval", 2, "parcial", True, "corona", "hormigon", "Óvalo con pista"),
    "Roma": e("oval", 2, "anillo", True, "corona", "membrana", "Olímpico con pista"),
    "Lazio": e("oval", 2, "anillo", True, "corona", "membrana", "Olímpico con pista"),
    "Atalanta": e("rect", 1, "parcial", False, "mixto", "metal", ""),
    "Fiorentina": e("oval", 1, "parcial", True, "torres", "hormigon", "Racionalista con su torre"),
    "Torino": e("oval", 1, "parcial", False, "torres", "hormigon", ""),
    "Bologna": e("oval", 2, "sin", False, "torres", "ladrillo", "Ladrillo rojo y torre de maratón"),
    "Udinese": e("rect", 1, "anillo", False, "halo", "metal", ""),
    "Sampdoria": e("ingles", 2, "anillo", False, "corona", "ladrillo", "Cuatro torres rojas en las esquinas"),
    "Genoa": e("ingles", 2, "anillo", False, "corona", "ladrillo", "Cuatro torres rojas en las esquinas"),
    "Lecce": e("oval", 1, "sin", False, "torres", "hormigon", ""),
    # ------------------------------------------------------------ ALEMANIA
    "Bayern Múnich": e("cuenco", 3, "total", False, "halo", "membrana", "Piel de membrana que se ilumina del color del club"),
    "Dortmund": e("ingles", 3, "anillo", False, "corona", "metal", "La muralla: el fondo de pie más grande de Europa"),
    "Leipzig": e("cuenco", 2, "anillo", False, "halo", "metal", "Cuenco dentro del viejo estadio"),
    "Leverkusen": e("rect", 2, "total", False, "halo", "metal", "Techado entero"),
    "Frankfurt": e("rect", 2, "retractil", False, "halo", "membrana", "Techo retráctil de membrana"),
    "Wolfsburgo": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Gladbach": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Friburgo": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Stuttgart": e("oval", 2, "membrana", False, "halo", "membrana", "Techo de membrana tensada"),
    "Unión Berlín": e("ingles", 1, "parcial", False, "torres", "hormigon", "En el bosque, casi todo de pie"),
    "Colonia": e("rect", 2, "anillo", False, "corona", "metal", "Cuatro torres de luz"),
    "Bremen": e("cuenco", 2, "anillo", False, "halo", "metal", "Junto al río"),
    # ------------------------------------------------------------ FRANCIA
    "Paris SG": e("cuenco", 2, "anillo", False, "halo", "hormigon", "Costillas de hormigón"),
    "Marsella": e("cuenco", 2, "membrana", False, "halo", "membrana", "Techo ondulado de membrana"),
    "Lyon": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Monaco": e("rect", 1, "parcial", False, "mixto", "hormigon", "Arcos en la tribuna de fondo"),
    "Lille": e("rect", 3, "retractil", False, "halo", "vidrio", "Techo retráctil"),
    "Niza": e("rect", 2, "anillo", False, "halo", "membrana", "Estructura de madera"),
    "Lens": e("ingles", 2, "anillo", False, "corona", "metal", "Estadio minero pegado al campo"),
    "Nantes": e("oval", 1, "parcial", False, "torres", "hormigon", ""),
    # ------------------------------------------------------------ BOLIVIA
    "Bolivar": e("oval", 2, "sin", True, "torres", "hormigon", "Estadio con pista a 3.600 m"),
    "The Strongest": e("oval", 2, "sin", True, "torres", "hormigon", "Estadio con pista a 3.600 m"),
    # ------------------------------------------------------------ JAPÓN
    "Kawasaki F.": e("oval", 1, "parcial", True, "torres", "hormigon", ""),
    "Yokohama FM": e("oval", 2, "parcial", True, "corona", "metal", "Coloso con pista"),
    "Kashima A.": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Urawa Reds": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Vissel Kobe": e("rect", 2, "retractil", False, "halo", "metal", "Techo retráctil"),
    "FC Tokio": e("oval", 2, "anillo", True, "corona", "metal", ""),
    # ------------------------------------------------------------ COREA
    "Ulsan HD": e("cuenco", 2, "anillo", False, "halo", "membrana", ""),
    "Jeonbuk M.": e("cuenco", 2, "anillo", False, "halo", "membrana", ""),
    "FC Seoul": e("rect", 2, "anillo", False, "halo", "membrana", "Techo como una cometa"),
    # ------------------------------------------------------------ ARABIA
    "Al-Hilal": e("oval", 2, "membrana", True, "corona", "membrana", "Techo de carpa del desierto"),
    "Al-Nassr": e("oval", 2, "membrana", True, "corona", "membrana", "Techo de carpa del desierto"),
    "Al-ittihad": e("cuenco", 2, "anillo", False, "halo", "vidrio", "La joya iluminada"),
    "Al-ahli SA": e("cuenco", 2, "anillo", False, "halo", "vidrio", "La joya iluminada"),
    # ------------------------------------------------------------ EGIPTO / MARRUECOS / SUDÁFRICA
    "Al Ahly": e("oval", 2, "sin", True, "torres", "hormigon", "Estadio internacional con pista"),
    "Zamalek": e("oval", 2, "sin", True, "torres", "hormigon", "Estadio internacional con pista"),
    "W. Casablanca": e("oval", 2, "parcial", True, "torres", "hormigon", ""),
    "Raja C.": e("oval", 2, "parcial", True, "torres", "hormigon", ""),
    "Orlando Pirates": e("cuenco", 3, "anillo", False, "corona", "membrana", "La calabaza: fachada de mosaico"),
    "Kaizer Chiefs": e("cuenco", 3, "anillo", False, "corona", "membrana", "La calabaza: fachada de mosaico"),
    "Mamelodi S.": e("rect", 2, "parcial", False, "mixto", "hormigon", ""),
    # ------------------------------------------------------------ AUSTRALIA
    "Sidney FC": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Melbourne City": e("rect", 2, "membrana", False, "halo", "membrana", "Techo de burbujas"),
    "Melbourne V.": e("rect", 2, "membrana", False, "halo", "membrana", "Techo de burbujas"),
    # ------------------------------------------------------------ MÉXICO
    "America": e("cuenco", 3, "parcial", False, "corona", "hormigon", "El coloso de tres bandejas"),
    "Cruz Azul": e("cuenco", 3, "parcial", False, "corona", "hormigon", "El coloso de tres bandejas"),
    "Tigres UANL": e("cuenco", 2, "sin", False, "torres", "hormigon", "El volcán"),
    "Monterrey": e("rect", 2, "anillo", False, "halo", "metal", "Con el cerro de fondo"),
    "Guadalajara": e("cuenco", 2, "anillo", False, "halo", "membrana", "Un volcán de césped por fuera"),
    "Pachuca": e("rect", 1, "sin", False, "torres", "hormigon", ""),
    "Toluca": e("rect", 2, "parcial", False, "mixto", "hormigon", ""),
    "Pumas UNAM": e("oval", 1, "sin", True, "torres", "hormigon", "Olímpico con mural"),
    "Santos Laguna": e("rect", 2, "anillo", False, "halo", "metal", ""),
    # ------------------------------------------------------------ EE. UU.
    "Inter Miami": e("rect", 1, "sin", False, "mixto", "metal", ""),
    "LAFC": e("rect", 2, "anillo", False, "halo", "metal", "Muro norte empinado"),
    "Seattle S.": e("rect", 2, "parcial", False, "halo", "metal", ""),
    "Columbus Crew": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "Atlanta Utd": e("cuenco", 3, "retractil", False, "halo", "vidrio", "Techo de pétalos retráctil"),
    "LA Galaxy": e("rect", 1, "parcial", False, "mixto", "metal", ""),
    "Portland T.": e("ingles", 2, "parcial", False, "torres", "metal", ""),
    "Orlando City": e("rect", 2, "anillo", False, "halo", "metal", ""),
    "FC Cincinnati": e("rect", 2, "anillo", False, "halo", "metal", ""),
}
