#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
HISTORIA DE LOS CLUBES CON GUIÑO (26-9-2026, pedido del usuario)
===============================================================

"La gracia de la historia es que nos haga entender a qué club quiere reflejar:
dar un guiño para entender qué equipo de nuestro juego es en la vida real."

Cada club del juego es la versión ficticia de uno real (`CLUBES` de
`base_ficticia.py`). Aquí va, por club real (nombre limpio, sin leetspeak):

    (año de fundación, apodo, apodo del estadio, guiño)

Cualquier campo puede ser None: `nucleo/historia_club.gd` lo rellena con la
historia generada. Los guiños evocan (apodos populares, barrios, hitos,
leyendas) sin usar escudos, marcas ni el nombre registrado del club.

`CLASICOS` son los partidos con nombre propio (Superclásico, Clásico
Universitario...). En la base ficticia se guardan con los nombres ficticios y
en el pack real con los reales.

Lo usa `base_ficticia.py` para escribir `HISTORIA_CLUBES` y `CLASICOS` en los
dos archivos. Los años de los clubes menos conocidos conviene revisarlos.
"""

H = {
    # ---------------------------------------------------------------- CHILE
    "Colo-Colo": (1925, "el Cacique", "la Ruca", "Lo fundaron jugadores rebeldes que se fueron de su club, y lleva el nombre de un sabio cacique mapuche. Es el Popular."),
    "U. de Chile": (1927, "el Romántico Viajero", "el Coloso de Ñuñoa", "Nació en la universidad pública; sus hinchas lo siguieron por todo Chile cuando no tenía casa propia."),
    "U. Católica": (1937, "los Cruzados", "la Fortaleza de la precordillera", "Nació en la universidad católica y juega a los pies de la cordillera, con la cruz en el pecho."),
    "Coquimbo Unido": (1958, "los Piratas", "el estadio frente a la bahía", "Puerto pirata del Norte Chico: su hinchada se viste de corsario."),
    "Cobresal": (1979, "los Mineros", "el estadio del campamento", "Nació en un campamento minero del cobre en pleno desierto y fue campeón contra todo pronóstico."),
    "Palestino": (1920, "el Tino-Tino", "La Cisterna", "Lo fundó la colonia palestina y lleva los colores de su bandera."),
    "Unión Española": (1897, "los Hispanos", "Santa Laura", "El club de la colonia española en Santiago, de los más antiguos del país."),
    "Audax Italiano": (1910, "los Tanos", "La Florida", "Lo fundó la colonia italiana: verde, blanco y rojo."),
    "Huachipato": (1947, "los Acereros", "el estadio de la usina", "Nació en la siderúrgica de Talcahuano: rayas azules y negras como el acero."),
    "Ñublense": (1916, "los Diablos Rojos", "el estadio de Chillán", "El orgullo rojo de Chillán."),
    "O'Higgins": (1955, "el Capo de Provincia", "El Teniente", "Celeste de Rancagua, con el nombre del prócer de la independencia."),
    "Everton": (1909, "los Ruleteros", "Sausalito", "Viñamarino fundado por descendientes de ingleses, con nombre de club inglés."),
    "D. Iquique": (1978, "los Dragones Celestes", "el estadio Tierra de Campeones", "Celeste frente al mar de Iquique, la Tierra de Campeones."),
    "U. La Calera": (1954, "los Cementeros", None, "Nació junto a la fábrica de cemento de La Calera."),
    "La Serena": (1955, "los Papayeros", "La Portada", "Granate de la ciudad de las papayas."),
    "D. Limache": (None, "los Tomateros", None, "Limache, tierra del tomate: por eso son los Tomateros."),
    "Cobreloa": (1977, "los Zorros del Desierto", "el estadio de Calama", "Nació en Calama al calor de la mina de cobre y jugó dos finales de la Libertadores."),
    "S. Wanderers": (1892, "el Decano", "Playa Ancha", "El club más antiguo de Chile en actividad, del puerto de Valparaíso."),
    "U. de Concepción": (1994, "el Campanil", None, "El equipo de la universidad penquista y su campanil."),
    "Rangers": (1902, "los Piducanos", "el Fiscal de Talca", "Rojinegro de Talca, de los más antiguos del sur."),
    "Magallanes": (1897, "la Academia", None, "Primer gran campeón del fútbol profesional chileno."),
    "Curicó Unido": (1973, "los Tortolitos", "La Granja", "El albirrojo de Curicó."),
    "Antofagasta": (1966, "los Pumas", None, "Celeste del Norte Grande."),
    "D. Concepción": (1966, "los Lilas", None, "El lila de Concepción."),
    "Stgo. Morning": (1903, "los Bohemios", None, "Club bohemio de la capital, con más de un siglo."),
    "San Luis": (1919, "los Canarios", None, "El amarillo de Quillota."),
    "D. Temuco": (1960, "el Pije", None, "El albiverde de la Araucanía."),
    "D. Copiapó": (1999, "el León de Atacama", None, "El león del desierto florido."),
    "San Marcos": (1978, "los Bravos del Morro", "el estadio mundialista de Arica", "Juega a la sombra del Morro de Arica, donde se jugó un Mundial."),
    "Recoleta": (None, None, None, "Club de barrio del norte de Santiago."),
    "Santa Cruz": (1913, None, None, "Del valle de Colchagua, tierra de vinos."),
    "Pto. Montt": (1983, "los Salmoneros", "Chinquihue", "Mirando al seno de Reloncaví."),
    # ------------------------------------------------------------ ARGENTINA
    "Boca Juniors": (1905, "los Xeneizes", "la Bombonera", "Lo fundaron inmigrantes genoveses en el barrio del puerto; los colores salieron de un barco sueco."),
    "River Plate": (1901, "los Millonarios", "el Monumental", "Nació en la ribera del río; la banda cruzada en el pecho es su sello."),
    "Racing Club": (1903, "la Academia", "el Cilindro", "Celeste y blanco de Avellaneda, primer grande argentino campeón del mundo."),
    "San Lorenzo": (1908, "el Ciclón", "el Nuevo Gasómetro", "Lo fundó un cura para sacar a los pibes de la calle en Almagro."),
    "Independiente": (1905, "el Rey de Copas", None, "El Rojo de Avellaneda: el que más Libertadores ganó."),
    "Estudiantes": (1905, "el Pincha", None, "Pincharratas de La Plata, tricampeón de América en los 60."),
    "Vélez": (1910, "el Fortín", None, "El Fortín de Liniers."),
    "Huracan": (1908, "el Globo", "el Palacio", "Un globo aerostático en el escudo, en Parque Patricios."),
    "Rosario Central": (1889, "el Canalla", "el Gigante de Arroyito", "Nació en el ferrocarril de Rosario."),
    "Newell's": (1903, "la Lepra", "el Coloso del Parque", "Lo fundaron en un colegio inglés de Rosario; cuna de un 10 inmortal."),
    "Lanús": (1915, "el Granate", "La Fortaleza", "El granate del sur del conurbano."),
    "Talleres": (1913, "la T", "el Mundialista de Córdoba", "Albiazul de Córdoba, nacido en los talleres del ferrocarril."),
    "Banfield": (1896, "el Taladro", None, "El verde y blanco del sur."),
    "Godoy Cruz": (1921, "el Tomba", None, "El Tomba de Mendoza, tierra de viñas."),
    "Colón": (1905, "el Sabalero", "el Cementerio de los Elefantes", "Rojinegro de Santa Fe: en su cancha caen los grandes."),
    "Unión SF": (1907, "el Tatengue", None, "El Tatengue de Santa Fe."),
    # --------------------------------------------------------------- BRASIL
    "Flamengo": (1895, "el Mengão", "el Maracaná", "Nació como club de remo en Río y tiene la hinchada más grande de Brasil."),
    "Palmeiras": (1914, "el Verdão", "la Arena del Parque", "Lo fundaron inmigrantes italianos en São Paulo."),
    "Sao Paulo": (1930, "el Tricolor Paulista", "el Morumbi", "Tricampeón del mundo, con su casa en el Morumbi."),
    "Gremio": (1903, "el Inmortal", None, "El tricolor gaúcho de Porto Alegre."),
    "Corinthians": (1910, "el Timão", None, "Lo fundaron obreros con el nombre de un club inglés que estaba de gira."),
    "Santos": (1912, "el Peixe", "la Vila", "El club del puerto donde brilló el Rey."),
    "Fluminense": (1902, "el Flu", "el Maracaná", "El club aristócrata de Laranjeiras."),
    "Botafogo": (1904, "la Estrella Solitaria", None, "La estrella solitaria de Río."),
    "Cruzeiro": (1921, "la Raposa", "el Mineirão", "Lo fundaron italianos en Belo Horizonte: cinco estrellas de la Cruz del Sur."),
    "Atl. Mineiro": (1908, "el Galo", None, "El gallo blanquinegro de Belo Horizonte."),
    "Internacional": (1909, "el Colorado", "el Beira-Rio", "A orillas del Guaíba, el Colorado gaúcho."),
    "Vasco": (1898, "el Gigante de la Colina", "São Januário", "Lo fundaron portugueses y fue de los primeros en aceptar jugadores negros."),
    "Bahia": (1931, "el Tricolor de Acero", "la Fonte Nova", "El tricolor de Salvador."),
    "Fortaleza": (1918, "el León del Pici", "el Castelão", "El león de Ceará."),
    "Athletico PR": (1924, "el Furacão", "la Baixada", "El huracán de Curitiba, con techo retráctil."),
    "Goiás": (1943, "el Verdão del Cerrado", "la Serrinha", "El verde del cerrado brasileño."),
    # -------------------------------------------------------------- URUGUAY
    "Peñarol": (1891, "los Carboneros", "el Campeón del Siglo", "Nació en el ferrocarril inglés de Montevideo: aurinegro."),
    "Nacional": (1899, "el Bolso", "el Gran Parque Central", "Primer club de criollos; su cancha vio el primer partido de un Mundial."),
    "Defensor": (1913, "el Violeta", None, "El violeta del Parque Rodó."),
    "Danubio": (1932, "la Franja", None, "Lo fundaron estudiantes de un liceo: franja negra en diagonal."),
    "Wanderers": (1902, "los Bohemios", None, "Albinegro bohemio del Prado."),
    "Liverpool M.": (1915, "los Negriazules", "el Belvedere", "Con nombre inglés, del barrio Belvedere."),
    "River (U)": (1932, "el Darsenero", None, "El de la Aguada."),
    "Cerro (U)": (1922, "el Villero", None, "Celeste y rojo de la Villa del Cerro."),
    "Boston River": (1939, "el Sastre", None, None),
    "Racing (U)": (1919, "la Academia de Sayago", None, None),
    "Progreso": (1917, "el Gaucho del Pantanoso", None, "El gaucho de La Teja."),
    "Fénix": (1916, "el Albivioleta", None, "El albivioleta de Capurro."),
    "Plaza Colonia": (1917, "los Patas Blancas", None, "Campeón sorpresa, del puerto de Colonia."),
    "Montevideo C.": (2007, "el Ciudadano", None, "Club joven de un grupo internacional."),
    "Juventud": (1935, "la Juve", None, "El de Las Piedras."),
    "Rentistas": (1933, "el Bicho Colorado", None, "El bicho colorado del Cerrito."),
    # ------------------------------------------------------------- PARAGUAY
    "Olimpia": (1902, "el Decano", "el estadio de Para Uno", "El decano del fútbol paraguayo, tricampeón de América."),
    "Cerro Porteño": (1912, "el Ciclón", "la Nueva Olla", "El ciclón de Barrio Obrero."),
    "Libertad": (1905, "el Gumarelo", "La Huerta", "El gumarelo de Asunción."),
    "Guarani": (1903, "el Legendario", None, "El Aborigen, de los más antiguos de Paraguay."),
    "Nacional (P)": (1904, "la Academia", None, None),
    "Sol de América": (1909, "el Danzarín", None, None),
    "Luqueño": (1921, "el Auriazul", None, "El auriazul de Luque."),
    "Doce de Octubre": (1914, None, None, "De Itauguá, tierra del ñandutí."),
    "Tacuari": (1923, None, None, "Club de barrio de Asunción, con nombre de río guaraní."),
    "Gral. Caballero": (None, None, None, "Del Alto Paraná, en la frontera con Brasil."),
    "Ameliano": (1936, None, None, "Del barrio Ameliano de Asunción, campeón de copa sorpresa."),
    "Trinidense": (None, "el Trini", None, None),
    "2 de Mayo": (1935, "el Gallo Norteño", None, "El gallo del norte, de Pedro Juan Caballero."),
    "Rubio Ñu": (1913, None, "La Arboleda", None),
    "Fernando Mora": (None, None, None, "De la ciudad vecina de Asunción que lleva el nombre de un prócer."),
    "Resistencia": (1917, None, None, None),
    # ------------------------------------------------------------- COLOMBIA
    "Atl. Nacional": (1947, "el Verdolaga", "el Atanasio", "El verde de Medellín, primer colombiano campeón de la Libertadores."),
    "Millonarios": (1946, "el Embajador", "El Campín", "El Ballet Azul de la época dorada."),
    "America de Cali": (1927, "la Mechita", "el Pascual", "Los diablos rojos de Cali, cinco finales de la Libertadores."),
    "Junior": (1924, "el Tiburón", "el Metropolitano", "El tiburón de la costa caribe."),
    "Santa Fe": (1941, "el Expreso Rojo", "El Campín", "El primer campeón del fútbol profesional colombiano."),
    "Dep. Cali": (1912, "los Azucareros", None, "El verde de la tierra de la caña."),
    "Tolima": (1954, "el Pijao", None, "El vinotinto y oro de Ibagué."),
    "DIM Medellin": (1913, "el Poderoso de la Montaña", "el Atanasio", "El rojo y azul de Medellín."),
    "Once Caldas": (1961, "el Blanco Blanco", "el Palogrande", "Campeón de América desde Manizales."),
    "Bucaramanga": (1949, "el Leopardo", None, "El leopardo santandereano."),
    "Pereira": (1944, "el Grande Matecaña", None, "El matecaña del Eje Cafetero."),
    "La Equidad": (1982, "los Aseguradores", None, "Club de una aseguradora bogotana."),
    "Envigado": (1989, "la Naranja Mecánica", None, "Cantera de cracks del Valle de Aburrá."),
    "Alianza FC": (None, None, None, "Del Caribe colombiano."),
    "Fortaleza C.": (None, None, None, "Club joven de Bogotá."),
    "Boyacá Chicó": (2002, "el Ajedrezado", None, "El ajedrezado de Tunja, campeón contra todo pronóstico."),
    # ----------------------------------------------------------------- PERÚ
    "Universitario": (1924, "los Cremas", "el Monumental", "Nació en la universidad de San Marcos: crema de Lima."),
    "Alianza Lima": (1901, "los Íntimos", "Matute", "El club del pueblo, en La Victoria."),
    "Sporting Cristal": (1955, "los Celestes", None, "Celeste del Rímac, nacido en una cervecería."),
    "Melgar": (1915, "el Dominó", None, "Rojinegro de la ciudad blanca de Arequipa."),
    "Cienciano": (1901, "el Papá", "el Garcilaso", "Campeón continental desde el Cusco."),
    "Sport Boys": (1927, "la Misilera", None, "El rosado del Callao."),
    "Municipal": (1935, "la Academia", None, "La franja de Lima."),
    "Cusco FC": (None, None, None, "Del Cusco imperial."),
    "C. Vallejo": (1996, "los Poetas", "el Mansiche", "Lleva el nombre de un poeta; de Trujillo."),
    "Atl. Grau": (1919, None, None, "El patrimonio de Piura."),
    "Garcilaso": (None, None, None, "Del Cusco, en la altura."),
    "AD Tarma": (None, None, None, "De la sierra central."),
    "UTC Cajamarca": (1964, "los Gavilanes", None, "De Cajamarca."),
    "Binacional": (2010, None, None, "De Juliaca, a más de 3.800 metros de altura."),
    "Ayacucho": (None, None, None, "De Ayacucho."),
    "Chankas": (None, None, None, "De Andahuaylas."),
    # -------------------------------------------------------------- ECUADOR
    "LDU Quito": (1930, "la Liga", "la Casa Blanca", "Primer ecuatoriano campeón de la Libertadores."),
    "Barcelona SC": (1925, "el Ídolo del Astillero", "el Monumental", "Lo fundaron inmigrantes catalanes en el barrio del Astillero."),
    "Emelec": (1929, "el Bombillo", "el Capwell", "Nació en la empresa eléctrica de Guayaquil."),
    "I. del Valle": (1958, "los Rayados del Valle", None, "Un proyecto de cantera que llegó a campeón de América."),
    "Aucas": (1945, "el Ídolo del Pueblo", None, "Nació en una petrolera de Quito."),
    "El Nacional": (1964, "los Puros Criollos", None, "El club de las Fuerzas Armadas que solo alineaba ecuatorianos."),
    "Delfin": (1989, "el Cetáceo", None, "De Manta, frente al Pacífico."),
    "U. Católica (E)": (1963, "el Trencito Azul", None, "El trencito azul universitario de Quito."),
    "Orense": (2009, "los Bananeros", None, "De Machala, capital bananera."),
    "Técnico U.": (1971, "el Rodillo Rojo", None, "De Ambato."),
    "Mushuc Runa": (2003, "el Ponchito", None, "El primer club indígena del fútbol profesional."),
    "Macara": (1939, "el Ídolo de Ambato", None, "Celeste de Ambato."),
    "Guayaquil C.": (2007, "los Ciudadanos", None, None),
    "Cumbaya": (None, None, None, "Del valle a las afueras de Quito."),
    "Imbabura": (1993, "los Leones del Norte", None, "De Ibarra."),
    "9 de Octubre": (1912, "el Patriota", None, "Lleva la fecha de la independencia de Guayaquil."),
    # --------------------------------------------------------------- ESPAÑA
    "Real Madrid": (1902, "los Merengues", "el Coliseo de la Castellana", "El de las Copas de Europa, blanco de pies a cabeza."),
    "Barcelona": (1899, "los Culés", "el Nou", "Lo fundó un suizo, y presume de ser más que un club."),
    "Atlético Madrid": (1903, "los Colchoneros", "el Metropolitano", "Rojiblanco como los colchones de antaño; nació como filial de un club vasco."),
    "Sevilla": (1890, "los Nervionenses", "el estadio de Nervión", "El rey de la Europa League."),
    "Valencia": (1919, "los Che", "el viejo estadio del Turia", "El murciélago del escudo, en la ciudad de la paella."),
    "Villarreal": (1923, "el Submarino Amarillo", "La Cerámica", "El submarino amarillo de un pueblo de azulejos."),
    "Ath. Bilbao": (1898, "los Leones", "La Catedral", "Solo juegan los de casa: la cantera como filosofía."),
    "Real Sociedad": (1909, "los Txuri-urdin", None, "Blanquiazul de Donostia."),
    "Betis": (1907, "los Verdiblancos", None, "Verdiblanco de Sevilla: manque pierda."),
    "Celta Vigo": (1923, "los Celestes", "Balaídos", "El celeste de la ría de Vigo."),
    "Getafe": (1983, "los Azulones", None, "Del sur de Madrid."),
    "Osasuna": (1920, "los Rojillos", "El Sadar", "El rojillo de Pamplona, tierra de sanfermines."),
    "Girona": (1930, "los Blanquivermells", "Montilivi", "A rayas rojiblancas, de la ciudad de los ríos."),
    "Mallorca": (1916, "los Bermellones", "Son Moix", "El isleño."),
    "Espanyol": (1900, "los Periquitos", None, "Lo fundaron estudiantes de Barcelona."),
    "Rayo Vallecano": (1924, "la Franja", "Vallecas", "El de la franja roja del barrio obrero."),
    # ------------------------------------------------------------ INGLATERRA
    "Manchester Utd": (1878, "los Diablos Rojos", "el Teatro de los Sueños", "Nació como club de los trabajadores del ferrocarril."),
    "City de Manch.": (1880, "los Citizens", "el estadio del este de Mánchester", "Nació en una parroquia; celeste de Mánchester."),
    "Liverpool": (1892, "los Reds", "el templo del «nunca caminarás solo»", "Nunca caminarás solo."),
    "Arsenal": (1886, "los Gunners", "el estadio del norte de Londres", "Lo fundaron obreros de una fábrica de armas."),
    "Chelsea": (1905, "los Blues", "el Puente", "Del oeste de Londres."),
    "Tottenham": (1882, "los Spurs", "la casa de la espuela", "El gallo sobre el balón, del norte de Londres."),
    "Newcastle": (1892, "las Urracas", "el parque de Santiago", "Albinegro del norte."),
    "Aston Villa": (1874, "los Villanos", "Villa Park", "Campeón de Europa en 1982."),
    "West Ham": (1895, "los Martillos", "el Estadio Olímpico", "Nació en un astillero: los martillos cruzados."),
    "Everton FC": (1878, "los Toffees", "el nuevo estadio del muelle", "Nació en una iglesia metodista."),
    "Brighton": (1901, "las Gaviotas", None, "Del sur, frente al mar."),
    "Wolves": (1877, "los Lobos", "Molineux", "Oro y negro de las Midlands."),
    "Cristal Palace": (1905, "las Águilas", "Selhurst Park", "Con el nombre del palacio de cristal de una exposición universal."),
    "Fulham": (1879, "los Cottagers", "la cabaña del Támesis", "La cabaña a orillas del Támesis."),
    "Brentford": (1889, "las Abejas", "la colmena", "Las abejas del oeste de Londres."),
    "Nottingham F.": (1865, "los Tricky Trees", "el City Ground", "Bicampeón de Europa en 1979 y 1980."),
    # ---------------------------------------------------------------- ITALIA
    "Juventus": (1897, "la Vecchia Signora", "la casa bianconera", "La fundaron estudiantes de liceo de Turín: la cebra en el escudo."),
    "Milan": (1899, "los Rossoneri", "la Scala del Calcio", "Lo fundaron ingleses: rojo del fuego y negro del miedo."),
    "Inter": (1908, "los Nerazzurri", "la Scala del Calcio", "Nació de una escisión, abierto a los extranjeros."),
    "Napoli": (1926, "los Partenopei", "el estadio del Diez", "Donde un 10 inmortal ganó dos títulos de liga."),
    "Roma": (1927, "la Loba", "el Olímpico", "La loba capitolina en el escudo."),
    "Lazio": (1900, "las Águilas", "el Olímpico", "El águila celeste de Roma."),
    "Atalanta": (1907, "la Diosa", None, "La diosa de Bérgamo, campeona europea."),
    "Fiorentina": (1926, "la Viola", "el estadio de Campo di Marte", "La violeta de Florencia."),
    "Torino": (1906, "el Toro", None, "Recuerda al Grande Torino, caído en Superga en 1949."),
    "Bologna": (1909, "los Rossoblù", None, "Rojiazul de Bolonia."),
    "Udinese": (1896, "los Friulanos", "el Friuli", "Blanquinegro del Friuli."),
    "Sampdoria": (1946, "la Samp", None, "Génova azul, con la franja de colores en el pecho."),
    "Genoa": (1893, "el Grifone", None, "El club más antiguo de Italia."),
    "Sassuolo": (1920, "los Neroverdi", None, "Club de una empresa de cerámica."),
    "Monza": (1912, "los Brianzoli", None, "La ciudad del circuito de Fórmula 1."),
    "Lecce": (1908, "los Giallorossi del sur", "el Via del Mare", "Del tacón de la bota."),
    # -------------------------------------------------------------- ALEMANIA
    "Bayern Múnich": (1900, "los Bávaros", "el estadio que cambia de color", "El gigante de Baviera."),
    "Dortmund": (1909, "los Aurinegros", "el Muro Amarillo", "Su grada de pie es la más grande de Europa."),
    "Leipzig": (2009, "los Toros Rojos", None, "Club nuevo con una bebida energética detrás."),
    "Leverkusen": (1904, "los Farmacéuticos", None, "Nació en una fábrica química y fue campeón invicto."),
    "Frankfurt": (1899, "las Águilas", "el estadio del bosque", "El águila de Fráncfort."),
    "Wolfsburgo": (1945, "los Lobos", "el estadio de la fábrica", "El club de la gran fábrica de autos."),
    "Gladbach": (1900, "los Potros", None, "Los potros de los años 70."),
    "Friburgo": (1904, "los de la Selva Negra", None, "De la Selva Negra."),
    "Stuttgart": (1893, "los Suabos", "el estadio del Neckar", "De la tierra de los autos de lujo."),
    "Hoffenheim": (1899, "los Aldeanos", None, "Un pueblo que llegó a la élite."),
    "Unión Berlín": (1966, "los de Hierro", "la casa del guardabosques", "Sus hinchas construyeron su propio estadio."),
    "Mainz": (1905, "los Carnavaleros", None, "La ciudad del carnaval."),
    "Colonia": (1948, "los Chivos", None, "Una cabra es su mascota de verdad."),
    "Bremen": (1899, "los Verdes del Weser", None, "A orillas del Weser."),
    "Bochum": (1848, "los Azules del Ruhr", None, "Del corazón minero del Ruhr."),
    "Augsburgo": (1907, "los Fuggerstädter", None, "De la ciudad de los banqueros Fugger."),
    # ---------------------------------------------------------------- FRANCIA
    "Paris SG": (1970, "los Parisinos", "el Parque de los Príncipes", "Joven y poderoso, campeón de Europa."),
    "Marsella": (1899, "el OM", "el Vélodrome", "Fue el primer francés campeón de Europa (1993)."),
    "Lyon": (1950, "los Gones", None, "Siete ligas seguidas a principios de siglo."),
    "Monaco": (1924, "los Monegascos", None, "Del principado, rojo y blanco en diagonal."),
    "Lille": (1944, "los Dogos", None, "El dogo del norte."),
    "Niza": (1904, "los Aiglons", None, "El aguilucho de la Costa Azul."),
    "Rennes": (1901, "los Rojinegros", None, "Bretones."),
    "Lens": (1906, "Sangre y Oro", "Bollaert", "Club minero: sangre y oro."),
    "Nantes": (1943, "los Canarios", "La Beaujoire", "El juego a la nantesa."),
    "Estrasburgo": (1906, "el Racing", "La Meinau", "De Alsacia."),
    "Toulouse": (1970, "los Violetas", None, "La ciudad rosa."),
    "Montpellier": (1974, "la Paillade", None, "Campeón sorpresa en 2012."),
    "Brest": (1950, "los Piratas", None, "Puerto bretón que llegó a la Champions."),
    "Reims": (1931, "los Rojos y Blancos", None, "Finalista de la primera Copa de Europa."),
    "Lorient": (1926, "las Merluzas", None, "Las merluzas del puerto."),
    "Auxerre": (1905, "el AJA", None, "Lo fundó un cura."),
    # --------------------------------------------------------------- BOLIVIA
    "Bolivar": (1925, "la Academia", None, "Celeste de La Paz, a 3.600 metros."),
    "The Strongest": (1908, "el Tigre", None, "El gualdinegro, el más antiguo de Bolivia en actividad."),
    "Always Ready": (1933, "la Banda Roja", None, "Juega en El Alto, a más de 4.000 metros."),
    "Blooming": (1946, "la Academia Cruceña", None, "Celeste de Santa Cruz."),
    "Oriente P.": (1955, "el Refinero", None, "Verde de Santa Cruz, nacido en una petrolera."),
    "Wilstermann": (1949, "el Aviador", None, "Club de aviadores de Cochabamba."),
    "San José": (1942, "el Santo", None, "Del Carnaval de Oruro."),
    "Guabira": (1962, "el Azucarero", None, "De Montero, tierra de la caña."),
    "Tomayapo": (None, None, None, "De Tarija."),
    "Nac. Potosí": (1942, None, None, "En Potosí, a casi 4.000 metros."),
    "Aurora": (1935, "el Equipo del Pueblo", None, "Celeste de Cochabamba."),
    "Indep. Petrolero": (1932, "el Matador", None, "De Sucre."),
    "R. Santa Cruz": (1962, None, None, None),
    "Palmaflor": (2008, None, None, "De Quillacollo."),
    "Vaca Diez": (None, None, None, "De Cobija, en la Amazonía."),
    "Univ. de Vinto": (None, None, None, "Del valle de Cochabamba, nacido de una universidad."),
    # ----------------------------------------------------------------- JAPÓN
    "Kawasaki F.": (1955, "los Delfines", None, "Nació como club de una empresa electrónica."),
    "Yokohama FM": (1972, "los Marinos", "el estadio de la final mundialista", "Tricolor del puerto de Yokohama."),
    "Kashima A.": (1947, "los Ciervos", None, "Un astro brasileño lo convirtió en potencia."),
    "Urawa Reds": (1950, "los Rojos", None, "Tricampeón de Asia, con la hinchada más ruidosa de Japón."),
    "Vissel Kobe": (1966, "los Barcos", None, "Del puerto de Kobe."),
    "Gamba Osaka": (1980, None, None, "Azul y negro de Osaka."),
    "FC Tokio": (1935, None, None, "Azul y rojo de la capital."),
    "Sanfrecce H.": (1938, "las Tres Flechas", None, "Tres flechas, tres hermanos: una vieja leyenda japonesa."),
    "Cerezo Osaka": (1957, "los Cerezos", None, "Rosa como la flor del cerezo."),
    "Nagoya G.": (1939, None, None, "El club de la gran fábrica de autos."),
    "Konsadole S.": (1935, "los Búhos", None, "De la nieve de Hokkaido."),
    "Avispa F.": (1982, "las Avispas", None, "Las avispas de Kyushu."),
    "Shimonoseki": (None, None, None, "Del estrecho entre dos islas."),
    "Kyoto S.": (1922, None, None, "De la antigua capital imperial."),
    "Albirex N.": (1955, "los Cisnes", "el Gran Cisne", "Naranja de Niigata."),
    "Shonan B.": (1968, None, None, "De la costa de Shonan."),
    # ----------------------------------------------------------------- COREA
    "Ulsan HD": (1983, "los Tigres", None, "Club de astilleros."),
    "Jeonbuk M.": (1994, "los Guerreros Verdes", None, "El gran dominador de su liga."),
    "Pohang S.": (1973, "los Acereros", None, "El club del acero."),
    "FC Seoul": (1983, None, None, "Rojinegro de la capital."),
    "Incheon Utd": (2003, None, None, "Club ciudadano del puerto."),
    "Daejeon H.": (1997, None, None, "De la ciudad de la ciencia."),
    "Gangwon FC": (2008, "los Osos", None, "De las montañas del este."),
    "Suon FC": (2003, None, None, "De la ciudad de la fortaleza."),
    "Gwangju FC": (2010, None, None, None),
    "Jeju United": (1982, "los Isleños", None, "De la isla volcánica."),
    "Daegu FC": (2002, None, None, "Club ciudadano."),
    "Gimcheon": (None, "los Soldados", None, "Juegan los futbolistas que hacen el servicio militar."),
    "Seongnam": (1989, None, None, "Siete veces campeón."),
    "Busan IPark": (1983, None, None, "Del puerto de Busan."),
    "Ansan G.": (2017, None, None, None),
    "Ch. Citizen": (None, None, None, "Club ciudadano del centro del país."),
    # ------------------------------------------------------------ ARABIA SAUDÍ
    "Al-Hilal": (1957, "el Líder", None, "El más ganador de Asia, azul de Riad."),
    "Al-Nassr": (1955, "el Mundial", None, "Amarillo de Riad, casa de estrellas veteranas."),
    "Al-ittihad": (1927, "el Tigre", None, "El decano de Yeda."),
    "Al-ahli SA": (1937, "el Real de Yeda", None, "Verde de Yeda."),
    "Al-Shabab": (1947, "los Leones Blancos", None, "De Riad."),
    "Al-Ettifaq": (1945, None, None, "De Dammam."),
    "Al-Taawoun": (1956, None, None, "De Buraydah."),
    "Al-Faiha": (1953, None, None, "De Al Majma'ah."),
    "Al-Raed": (1954, None, None, "De Buraydah."),
    "Al-Fateh": (1958, None, None, "De Al-Hasa, el gran oasis."),
    "Dammac": (1972, None, None, "De Khamis Mushait, en las montañas del sur."),
    "Al-Khaleej": (1945, None, None, "De Saihat, en el golfo."),
    "Al-Wehda": (1945, None, None, "De La Meca."),
    "Al-Okgdood": (1976, None, None, "De Najrán."),
    "Al-Riyadh": (1954, None, None, "De Riad."),
    "Al-Hazem": (1957, None, None, "De Al Rass."),
    # ----------------------------------------------------------------- EGIPTO
    "Al Ahly": (1907, "el Club del Siglo", None, "El más laureado de África, rojo de El Cairo."),
    "Zamalek": (1911, "los Caballeros Blancos", None, "Blanco de El Cairo."),
    "Pyramids": (2008, None, None, "Club nuevo con vista a las pirámides."),
    "Ismaiiy": (1924, "los Brasileños", None, "Amarillo al estilo brasileño, a orillas del canal de Suez."),
    "Al Masry": (1920, None, None, "Verde de Port Said."),
    "Ceramica C.": (2007, "los Ceramistas", None, None),
    "Fut. Rise": (None, None, None, "Club nuevo de la ciudad nueva de El Cairo."),
    "National Bank": (None, None, None, "Club de un banco de El Cairo."),
    "ENPPi": (1985, "los Petroleros", None, None),
    "Pharco": (None, None, None, "Club de una farmacéutica."),
    "Smouha": (1949, None, None, "De Alejandría."),
    "El Gouna": (2003, None, None, "De un balneario del mar Rojo."),
    "Baladiyat": (None, None, None, "Del delta del Nilo, club de una ciudad textil."),
    "Talaea": (None, None, None, "El club del Ejército."),
    "Al Mokawloon": (1973, "los Contratistas", None, "Club de una gran constructora."),
    "ZED FC": (None, None, None, "Proyecto joven de las afueras de El Cairo."),
    # --------------------------------------------------------------- MARRUECOS
    "W. Casablanca": (1937, "los Rojos", "el estadio de Casablanca", "Rojo de Casablanca, campeón de África."),
    "Raja C.": (1949, "las Águilas Verdes", "el estadio de Casablanca", "Verde de Casablanca."),
    "AS FAR": (1958, "los Militares", None, "El club de las Fuerzas Armadas, en Rabat."),
    "RS Berkane": (1938, "los Naranjas", None, "Naranja del este, campeón continental."),
    "Maghreb Fès": (1946, None, None, "De la ciudad imperial de Fez."),
    "MC Oujda": (1946, None, None, "Del este, junto a la frontera."),
    "FUS Rabat": (1946, None, None, "De Rabat."),
    "Hassania A.": (1946, None, None, "De Agadir."),
    "Olympic Safi": (1921, None, None, "Del puerto de Safi."),
    "Chabab MA": (None, None, None, "Del Medio Atlas, entre montañas."),
    "Jeunesse S.": (None, None, None, "De un pueblo cerca de Casablanca que llegó a primera."),
    "SCC Mohammédia": (None, None, None, "De Mohammedia."),
    "Ittihad Tanger": (1983, None, None, "De Tánger, frente al estrecho."),
    "Renaissance Z.": (None, None, None, "De la llanura agrícola de Doukkala."),
    "Unión Touarga": (None, None, None, "Del barrio del palacio real de Rabat."),
    "COD Meknès": (1962, None, None, "De Mequinez."),
    # ------------------------------------------------------------ SUDÁFRICA
    "Mamelodi S.": (1970, "los Brasileños", None, "Amarillo de Pretoria, campeón de África."),
    "Orlando Pirates": (1937, "los Bucaneros", None, "La calavera del Soweto."),
    "Kaizer Chiefs": (1970, "Amakhosi", "la Ciudad del Fútbol", "Lo fundó un exjugador al volver de jugar en América."),
    "Stelleribosch": (2016, None, None, "De la tierra de los viñedos."),
    "Sekhukhune": (None, None, None, "De Limpopo, con nombre de un rey pedi."),
    "Cape Town City": (2016, "los Ciudadanos", None, "De Ciudad del Cabo."),
    "Supersport Utd": (1985, None, None, "De Pretoria."),
    "Richards Bay": (None, None, None, "Del puerto de KwaZulu-Natal."),
    "Golden Arrows": (1943, None, None, "De Durban."),
    "Polokwane": (None, None, None, "De la capital de Limpopo."),
    "Chippa Utd": (None, None, None, "Los Chilli Boys del Cabo Oriental."),
    "AmaZalu": (1932, "Usuthu", None, "De Durban."),
    "Ts. Galaxie": (2015, None, None, None),
    "Maritzburg": (1979, None, None, None),
    "Casric Stars": (None, None, None, "De Mpumalanga."),
    "Magesi FC": (None, None, None, "Recién ascendido desde Limpopo."),
    # ------------------------------------------------------------- AUSTRALIA
    "Melbourne City": (2009, "los Celestes", None, "Parte de un grupo de clubes celestes por todo el mundo."),
    "Sidney FC": (2004, None, None, "El más ganador de su liga."),
    "Melbourne V.": (2004, "la Gran V", None, "Azul marino de Melbourne."),
    "C. Coast M.": (2004, "los Marineros", None, "De la costa central."),
    "W. Sidney W.": (2012, "los Wanderers", None, "Campeón de Asia en su segunda temporada."),
    "Adelaide Utd": (2003, "los Rojos", None, "De la ciudad de las iglesias."),
    "Brisbane R.": (1957, "el Rugido", None, "Naranja de Queensland."),
    "Wellington P.": (2007, "el Fénix", None, "Neozelandés en una liga australiana."),
    "Macarthur FC": (2017, "los Toros", None, None),
    "Newcastle J.": (2000, "los Jets", None, None),
    "Perth Glory": (1995, "la Gloria", None, "De la otra costa."),
    "W. United": (2017, None, None, None),
    "Auckland FC": (2024, None, None, "El club más nuevo de la liga."),
    "Canberra Utd": (None, None, None, "De la capital."),
    "Geelong FC": (None, None, None, "De la bahía de Corio, al lado de Melbourne."),
    "Darwin City": (None, None, None, "Del norte tropical."),
    # ------------------------------------------------------------------ MÉXICO
    "America": (1916, "las Águilas", "el Coloso de Santa Úrsula", "El más odiado y el más querido de la capital."),
    "Tigres UANL": (1960, "los Felinos", "el Volcán", "Universitario de Monterrey, con el Volcán rugiendo."),
    "Monterrey": (1945, "los Rayados", "el Gigante de Acero", "Con vista al Cerro de la Silla."),
    "Guadalajara": (1906, "el Rebaño Sagrado", None, "Solo juegan mexicanos."),
    "Cruz Azul": (1927, "la Máquina Celeste", None, "Nació en una cementera de Hidalgo."),
    "Pachuca": (1901, "los Tuzos", "la Bella Airosa", "La cuna del fútbol mexicano, traído por mineros ingleses."),
    "Toluca": (1917, "los Diablos Rojos", "la Bombonera del Nevado", "Rojo de la ciudad más alta de la liga."),
    "Santos Laguna": (1983, "los Guerreros", None, "De la Comarca Lagunera."),
    "Pumas UNAM": (1954, "los Pumas", "el Olímpico Universitario", "La universidad nacional, cantera de cracks."),
    "Leon": (1944, "la Fiera", None, "Verde del Bajío."),
    "Atlas": (1916, "los Zorros", "el Jalisco", "Lo fundaron jóvenes que estudiaron en Inglaterra."),
    "Necaxa": (1923, "los Rayos", None, "Nació en una compañía eléctrica: los Once Hermanos."),
    "Puebla": (1944, "la Franja", None, "La franja azul de Puebla."),
    "Tijuana": (2007, "los Xolos", None, "Club de la frontera, con un perro xoloitzcuintle de mascota."),
    "Queretaro": (1950, "los Gallos Blancos", "La Corregidora", "Gallos del Bajío."),
    "Mazatlán": (2020, "los Cañoneros", "El Encanto", "Club del puerto, de los más jóvenes."),
    # ------------------------------------------------------------ ESTADOS UNIDOS
    "Inter Miami": (2018, "las Garzas", None, "Rosa y negro, con un crack rosarino en sus filas."),
    "LAFC": (2014, "los Negro y Oro", None, "El otro club de Los Ángeles."),
    "Seattle S.": (2007, "los Sonidos", None, "Primer club de su liga campeón de la Concachampions."),
    "Columbus Crew": (1994, "los Obreros", None, "Estrenó el primer estadio solo de fútbol de su liga."),
    "Philadelphia U.": (2008, "la Unión", None, "Una serpiente en el escudo."),
    "Atlanta Utd": (2014, "las Cinco Rayas", None, "Estadio con techo de pétalos."),
    "LA Galaxy": (1994, "la Galaxia", None, "El más ganador de su liga."),
    "NY City FC": (2013, None, None, "Del grupo de los celestes, en el Bronx."),
    "N. England R.": (1994, "los Revs", None, None),
    "Austin FC": (2018, "los Verdes", None, None),
    "Portland T.": (2009, "los Leñadores", None, "Un leñador corta un tronco tras cada gol."),
    "Orlando City": (2010, "los Leones", None, "Violeta de Florida."),
    "FC Cincinnati": (2015, None, None, None),
    "Nashville SC": (2016, "los Coyotes", None, "De la ciudad de la música."),
    "St. Louis City": (2019, None, None, None),
    "Charlotte FC": (2019, "la Corona", None, None),
}

## Partidos con nombre propio: [club real, club real, nombre].
CLASICOS = [
    ["Colo-Colo", "U. de Chile", "Superclásico"],
    ["U. de Chile", "U. Católica", "Clásico Universitario"],
    ["U. Católica", "Colo-Colo", "el Clásico"],
    ["Everton", "S. Wanderers", "Clásico Porteño"],
    ["Cobreloa", "Cobresal", "Clásico del Cobre"],
    ["U. de Concepción", "D. Concepción", "Clásico Penquista"],
    ["Palestino", "Unión Española", "Clásico de colonias"],
    ["Audax Italiano", "Unión Española", "Clásico de colonias"],
    ["Boca Juniors", "River Plate", "Superclásico"],
    ["Racing Club", "Independiente", "Clásico de Avellaneda"],
    ["San Lorenzo", "Huracan", "Clásico de barrio"],
    ["Rosario Central", "Newell's", "Clásico rosarino"],
    ["Colón", "Unión SF", "Clásico santafesino"],
    ["Banfield", "Lanús", "Clásico del sur"],
    ["Flamengo", "Fluminense", "Fla-Flu"],
    ["Flamengo", "Vasco", "Clásico de los Millones"],
    ["Palmeiras", "Corinthians", "Derbi paulista"],
    ["Sao Paulo", "Corinthians", "Majestoso"],
    ["Gremio", "Internacional", "Gre-Nal"],
    ["Cruzeiro", "Atl. Mineiro", "Clásico mineiro"],
    ["Peñarol", "Nacional", "el Clásico"],
    ["Olimpia", "Cerro Porteño", "Superclásico"],
    ["Atl. Nacional", "DIM Medellin", "Clásico paisa"],
    ["Millonarios", "Santa Fe", "Clásico capitalino"],
    ["America de Cali", "Dep. Cali", "Clásico vallecaucano"],
    ["Universitario", "Alianza Lima", "el Clásico"],
    ["Barcelona SC", "Emelec", "Clásico del Astillero"],
    ["LDU Quito", "Aucas", "Clásico capitalino"],
    ["Real Madrid", "Barcelona", "el Clásico"],
    ["Atlético Madrid", "Real Madrid", "Derbi madrileño"],
    ["Sevilla", "Betis", "Gran Derbi"],
    ["Ath. Bilbao", "Real Sociedad", "Derbi vasco"],
    ["Barcelona", "Espanyol", "Derbi barcelonés"],
    ["Manchester Utd", "Liverpool", "Clásico del noroeste"],
    ["Manchester Utd", "City de Manch.", "Derbi de Mánchester"],
    ["Liverpool", "Everton FC", "Derbi de Merseyside"],
    ["Arsenal", "Tottenham", "Derbi del norte de Londres"],
    ["Inter", "Milan", "Derbi de la Madonnina"],
    ["Roma", "Lazio", "Derbi de la Capital"],
    ["Juventus", "Inter", "Derbi de Italia"],
    ["Juventus", "Torino", "Derbi de la Mole"],
    ["Genoa", "Sampdoria", "Derbi de la Linterna"],
    ["Bayern Múnich", "Dortmund", "el Clásico alemán"],
    ["Colonia", "Gladbach", "Derbi del Rin"],
    ["Paris SG", "Marsella", "el Clásico francés"],
    ["Lens", "Lille", "Derbi del Norte"],
    ["Niza", "Monaco", "Derbi de la Costa Azul"],
    ["Bolivar", "The Strongest", "Clásico paceño"],
    ["Blooming", "Oriente P.", "Clásico cruceño"],
    ["Aurora", "Wilstermann", "Clásico cochabambino"],
    ["Gamba Osaka", "Cerezo Osaka", "Derbi de Osaka"],
    ["Ulsan HD", "Pohang S.", "Derbi de la costa este"],
    ["Al-Hilal", "Al-Nassr", "Derbi de Riad"],
    ["Al-ittihad", "Al-ahli SA", "Derbi de Yeda"],
    ["Al Ahly", "Zamalek", "Derbi de El Cairo"],
    ["W. Casablanca", "Raja C.", "Derbi de Casablanca"],
    ["Orlando Pirates", "Kaizer Chiefs", "Derbi del Soweto"],
    ["Sidney FC", "W. Sidney W.", "Derbi de Sídney"],
    ["Melbourne City", "Melbourne V.", "Derbi de Melbourne"],
    ["America", "Guadalajara", "Clásico nacional"],
    ["Tigres UANL", "Monterrey", "Clásico regio"],
    ["America", "Pumas UNAM", "Clásico capitalino"],
    ["Guadalajara", "Atlas", "Clásico tapatío"],
    ["America", "Cruz Azul", "Clásico joven"],
    ["LA Galaxy", "LAFC", "el Tráfico"],
    ["Seattle S.", "Portland T.", "Derbi de Cascadia"],
]

CAMPOS = ("fundado", "apodo", "estadio", "guino")


def _fila(t):
    return {k: v for k, v in zip(CAMPOS, t) if v is not None}


def tablas(clubes_real_a_ficticio, limpiar):
    """Devuelve (base, pack): cada uno {"HISTORIA_CLUBES": {...}, "CLASICOS": [...]}.

    `clubes_real_a_ficticio` es `CLUBES` de base_ficticia.py (nombre real limpio
    -> nombre ficticio). Las claves de H también van limpias.
    """
    faltan = [k for k in H if k not in clubes_real_a_ficticio]
    if faltan:
        raise SystemExit("historia_clubes: clubes sin equivalente ficticio: %s" % faltan)
    base_h = {clubes_real_a_ficticio[k]: _fila(v) for k, v in H.items()}
    pack_h = {k: _fila(v) for k, v in H.items()}
    base_c, pack_c = [], []
    for a, b, n in CLASICOS:
        for x in (a, b):
            if x not in clubes_real_a_ficticio:
                raise SystemExit("historia_clubes: clásico con club desconocido: %s" % x)
        base_c.append([clubes_real_a_ficticio[a], clubes_real_a_ficticio[b], n])
        pack_c.append([a, b, n])
    return ({"HISTORIA_CLUBES": base_h, "CLASICOS": base_c},
            {"HISTORIA_CLUBES": pack_h, "CLASICOS": pack_c})
